fieldLayouts:
  322c9a8f-5782-4020-88bf-06e529f95d44:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1a8b5921-e958-4ba4-b0c7-19a0f71c9f19
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14ca6448-a622-4080-927f-a09cdee34d0c # Post Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c902a11-dc93-4894-937f-812ed173a762
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: aacaab41-2e81-4f36-a640-48c0f083c188 # Post Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef9174a9-c87e-4e21-b43e-aa79c8ab13aa
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: db3eb15e-d31d-42d8-a096-ea59770b5875 # Post header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4834d49-0b3d-459b-944b-9af26898961b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 59e9b836-d326-4589-8b89-c748eb5ae5d2 # Post Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2376ab56-6a4a-41ed-87a8-9fcea96d5cc3
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 895eb9af-0929-4ed0-8cb7-ef9f800f6ddb # Blog Editor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 068544a7-1d79-4cdf-9b8e-2ed66d652822
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a0c0d42d-fa32-40b4-82b7-deeba5cb57a6
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: a3e720fe-976f-4bd7-ba58-6aa958bf03d0 # Blog Post
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
