childBlocks: null
conditions: null
description: ''
enabled: true
field: 4a2e3929-984b-40ff-96fb-0d1322e1cafe # Content
fieldLayouts:
  0cfac71d-039c-4e40-adbf-4be5fcbe051e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f5939e68-fb8c-45ac-a02c-ee707315e133 # Vimeo Video Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2088d1ab-259e-4e1b-a0c8-9073d1913341
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3211d176-3a68-4fe6-9671-f8dfab0868f9
        userCondition: null
group: null
groupChildBlockTypes: true
handle: video
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Video
sortOrder: 21
topLevel: true
