columnSuffix: awzotesu
contentColumnType: text
fieldGroup: 8e54d255-9214-4889-8d34-f3ae16facab1 # Reusable Fields
handle: vimeoVideoCode
instructions: 'The url after https://vimeo.com/'
name: 'Vimeo Video Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: '898173978'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
